version: '3.8'
services:
  app_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

  html_service:
    build:
      context: ./public/html
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app_network


  js_service:
    build:
      context: ./public/js
      dockerfile: Dockerfile
    ports:
      - "8083:3000"
    networks:
      - app_network

  json_service:
    build:
      context: ./public/json
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
  videos_service:
    build:
      context: ./public/videos
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

